export interface WalkthroughFeatureStep {
  id: string;
  stepNumber: string;
  title: string;
  shortName: string;
  category: string;
  description: string;
}

export interface ModuleWalkthroughData {
  slug: string;
  badge: string;
  eyebrow: string;
  heading: string;
  subtitle: string;
  features: WalkthroughFeatureStep[];
}

export const moduleWalkthroughDatasets: Record<string, ModuleWalkthroughData> = {
  crm: {
    slug: "crm",
    badge: "CRM & Pipeline Automation",
    eyebrow: "POWERFUL CRM CAPABILITIES",
    heading: "Everything your sales team needs to close deals faster.",
    subtitle: "Explore how Warrgyizmorsch CRM connects prospect pipelines, lead scoring, 360° customer accounts, and automated conversion.",
    features: [
      {
        id: "dashboard",
        stepNumber: "01",
        title: "CRM Executive Dashboard",
        shortName: "Executive Dashboard",
        category: "Executive Overview",
        description: "Real-time B2B & B2C analytics, active pipeline valuation, closed revenue, and automated WhatsApp lead engagement status.",
      },
      {
        id: "leads",
        stepNumber: "02",
        title: "Lead Capture & Prospect Qualification",
        shortName: "Leads",
        category: "Lead Acquisition",
        description: "Capture and manage leads with multi-channel sources, contact scoring, owner assignment, and automated tracking.",
      },
      {
        id: "pipeline",
        stepNumber: "03",
        title: "Visual Deals & Pipeline Management",
        shortName: "Deals (Pipeline)",
        category: "Kanban & Pipeline",
        description: "Manage prospective deals through an interactive visual Kanban board with stage progression, win probabilities, and revenue metrics.",
      },
      {
        id: "accounts",
        stepNumber: "04",
        title: "Enterprise Accounts & Corporate Directory",
        shortName: "Accounts (Companies)",
        category: "Account Master",
        description: "Maintain complete corporate account profiles with multiple contact persons, GSTIN/PAN records, and credit limits.",
      },
      {
        id: "customers",
        stepNumber: "05",
        title: "Customer Success 360°",
        shortName: "Customers",
        category: "Customer Master",
        description: "Track customer retention, contract lifecycle, lifetime revenue value (CLV), and SLA compliance.",
      },
      {
        id: "tracker",
        stepNumber: "06",
        title: "Activities & Communication Feed",
        shortName: "Activities",
        category: "Omnichannel Log",
        description: "Track sales follow-ups, calls, tasks, meeting notes, and prospect progress from a single unified activity timeline.",
      },
      {
        id: "status",
        stepNumber: "07",
        title: "Pipeline SLA & Track Status",
        shortName: "Track Status",
        category: "Pipeline SLA",
        description: "Monitor real-time status progression, turnaround speed, and pipeline bottlenecks across all active sales reps.",
      },
      {
        id: "masters",
        stepNumber: "08",
        title: "CRM Masters & Custom Workflows",
        shortName: "CRM Masters",
        category: "Sales Governance",
        description: "Configure sales workflows, lead statuses, deal stages, and industry-specific classifications aligned strictly with your operational process.",
      },
    ],
  },
  sales: {
    slug: "sales",
    badge: "Sales & Order Governance",
    eyebrow: "POWERFUL SALES CAPABILITIES",
    heading: "From multi-item CPQ quotes to GST invoices & dispatch.",
    subtitle: "Streamline customer quotes, multi-level discount approvals, automated GST splitting, and E-Way bill dispatch.",
    features: [
      {
        id: "quotation",
        stepNumber: "01",
        title: "Multi-Item CPQ Quotation Creation",
        shortName: "CPQ Quotations",
        category: "Price Quotations",
        description: "Generate multi-item quotations with instant margin calculation, custom price lists, volume discounts, and payment terms.",
      },
      {
        id: "approval",
        stepNumber: "02",
        title: "Quotation Approval & Workflow",
        shortName: "Approval Workflow",
        category: "Commercial Control",
        description: "Enforce multi-tier approval rules for custom discounts and special credit terms before quotations are dispatched to clients.",
      },
      {
        id: "gst",
        stepNumber: "03",
        title: "GST & Commercial Controls",
        shortName: "GST Tax Matrix",
        category: "Tax Compliance",
        description: "Automate state-wise CGST, SGST, IGST calculations, tax-exempt rules, and freight charge allocations on every order.",
      },
      {
        id: "order",
        stepNumber: "04",
        title: "Sales Order & Dispatch Execution",
        shortName: "Sales Orders",
        category: "Order Processing",
        description: "Convert accepted quotes into binding sales orders, generate picking lists, and issue tax invoices with E-Way bill metadata.",
      },
      {
        id: "returns",
        stepNumber: "05",
        title: "Payments & Returns Allocation",
        shortName: "Receipts & Credit Notes",
        category: "Accounts Receivable",
        description: "Process customer advance receipts, balance invoice allocations, sales returns, and credit note issuance seamlessly.",
      },
    ],
  },
  purchase: {
    slug: "purchase",
    badge: "Procurement & Vendor Management",
    eyebrow: "POWERFUL PROCUREMENT CAPABILITIES",
    heading: "Automate material demand, RFQs, and 3-way invoice matching.",
    subtitle: "Consolidate purchase requisitions, compare supplier quotes side-by-side, and clear audit-ready 3-way matches.",
    features: [
      {
        id: "demand",
        stepNumber: "01",
        title: "Purchase Requisition & Material Demand",
        shortName: "PR Requisition",
        category: "Demand Consolidation",
        description: "Auto-generate purchase requisitions based on safety stock thresholds, job orders, and reorder point alerts.",
      },
      {
        id: "rfq",
        stepNumber: "02",
        title: "RFQ & 3-Way Supplier Comparison",
        shortName: "RFQ Comparison",
        category: "Supplier Sourcing",
        description: "Send RFQs to multiple vendors and evaluate side-by-side comparison tables based on unit price, lead time, and vendor rating.",
      },
      {
        id: "po",
        stepNumber: "03",
        title: "Purchase Order Release & Authorization",
        shortName: "PO Issuance",
        category: "Order Authorization",
        description: "Issue legally binding purchase orders with automated multi-level approval hierarchies and vendor delivery schedules.",
      },
      {
        id: "match",
        stepNumber: "04",
        title: "Three-Way Matching Clearance",
        shortName: "3-Way Match",
        category: "Audit Governance",
        description: "Verify Purchase Orders against Goods Receipt Notes (GRN) and Vendor Invoices before clearing payment authorization.",
      },
      {
        id: "payments",
        stepNumber: "05",
        title: "Vendor Payments & Debit Notes",
        shortName: "Vendor Payables",
        category: "Accounts Payable",
        description: "Manage advance vendor payments, scheduled payment runs, purchase return debit notes, and open ledger balances.",
      },
    ],
  },
  inventory: {
    slug: "inventory",
    badge: "Warehouse & Stock Control",
    eyebrow: "POWERFUL INVENTORY CAPABILITIES",
    heading: "Real-time stock visibility, FEFO batching & quarantine.",
    subtitle: "Track multi-warehouse stock levels, automate QA inspection gates, and trigger MRP shortage reorders instantly.",
    features: [
      {
        id: "dashboard",
        stepNumber: "01",
        title: "Multi-Warehouse Stock Dashboard",
        shortName: "Stock Control",
        category: "Warehouse Overview",
        description: "Monitor real-time bin locations, warehouse capacity utilization, material movement, and pending dispatch queues.",
      },
      {
        id: "grn",
        stepNumber: "02",
        title: "Goods Receipt & Quality Inspection",
        shortName: "GRN Inspection",
        category: "Inbound Receiving",
        description: "Receive inward material against POs and route through quality inspection checklists before updating stock balances.",
      },
      {
        id: "quarantine",
        stepNumber: "03",
        title: "Quality Quarantine Management",
        shortName: "QA Quarantine",
        category: "Quality Governance",
        description: "Isolate rejected or pending materials in quarantine bins with disposition routing for return-to-vendor or rework.",
      },
      {
        id: "mrp",
        stepNumber: "04",
        title: "MRP & Stock Shortage Auto-Reorder",
        shortName: "MRP Reorder",
        category: "Replenishment",
        description: "Calculate material shortage balances against incoming demand and auto-trigger purchase requisitions in one click.",
      },
      {
        id: "fefo",
        stepNumber: "05",
        title: "Batch, Serial & FEFO Expiry Movement",
        shortName: "Batch & FEFO",
        category: "Traceability",
        description: "Track lot numbers, manufacturing dates, expiry dates, and serial numbers with automated First-Expiry-First-Out picking.",
      },
    ],
  },
  production: {
    slug: "production",
    badge: "Manufacturing & Shopfloor",
    eyebrow: "POWERFUL PRODUCTION CAPABILITIES",
    heading: "Multi-level BOMs, work center routing & shopfloor OEE.",
    subtitle: "Plan manufacturing runs, verify readiness checklists, track active machine jobs, and monitor plant OEE analytics.",
    features: [
      {
        id: "bom",
        stepNumber: "01",
        title: "Multi-Level Bill of Materials (BOM)",
        shortName: "BOM Hierarchy",
        category: "Engineering Master",
        description: "Configure multi-tier BOM assembly trees with sub-assemblies, raw material quantities, scrap percentages, and item costs.",
      },
      {
        id: "readiness",
        stepNumber: "02",
        title: "Production Planning & Readiness Checklist",
        shortName: "Production Readiness",
        category: "Plan Execution",
        description: "Verify material availability, machine status, WIP readiness, and quality specifications before releasing work orders.",
      },
      {
        id: "routing",
        stepNumber: "03",
        title: "Work Center Routing & Machine Schedules",
        shortName: "Work Center Routing",
        category: "Shopfloor Operations",
        description: "Route jobs across sequential work centers (Cutting, Machining, Assembly, QA) with cycle times and setup metrics.",
      },
      {
        id: "cockpit",
        stepNumber: "04",
        title: "Shopfloor Operator Execution Cockpit",
        shortName: "Operator Cockpit",
        category: "Shopfloor Control",
        description: "Empower station operators with digital job cards, start/pause/complete actions, and real-time scrap logging.",
      },
      {
        id: "oee",
        stepNumber: "05",
        title: "OEE & Manufacturing Analytics",
        shortName: "OEE & Plant KPI",
        category: "Plant Performance",
        description: "Measure Overall Equipment Effectiveness (OEE), Availability, Performance, and Quality metrics across work centers.",
      },
    ],
  },
  accounting: {
    slug: "accounting",
    badge: "Financial Accounting & Ledger",
    eyebrow: "POWERFUL ACCOUNTING CAPABILITIES",
    heading: "Double-entry GL, automated bank reconciliation & GSTR.",
    subtitle: "Maintain audit-ready General Ledgers, post accounting vouchers, reconcile bank feeds, and file GST returns.",
    features: [
      {
        id: "chart",
        stepNumber: "01",
        title: "Multi-Tier Chart of Accounts (CoA)",
        shortName: "Chart of Accounts",
        category: "General Ledger",
        description: "Structure flexible multi-tiered accounts across Assets, Liabilities, Equity, Revenue, and Expenses with cost center tagging.",
      },
      {
        id: "gl",
        stepNumber: "02",
        title: "Double-Entry General Ledger Engine",
        shortName: "Double-Entry GL",
        category: "Financial Postings",
        description: "Automate real-time double-entry debit and credit journal entries triggered directly by operational invoices and receipts.",
      },
      {
        id: "vouchers",
        stepNumber: "03",
        title: "Accounting Vouchers & Financial Adjustments",
        shortName: "Accounting Vouchers",
        category: "Voucher Governance",
        description: "Post Payment, Receipt, Contra, Journal, Debit Note, and Credit Note vouchers with Maker-Checker approval controls.",
      },
      {
        id: "reconciliation",
        stepNumber: "04",
        title: "Automated Bank Statement Reconciliation",
        shortName: "Bank Reconciliation",
        category: "Cash & Treasury",
        description: "Match electronic bank statement feeds against internal general ledger accounts with automated rule-based reconciliation.",
      },
      {
        id: "gst",
        stepNumber: "05",
        title: "GSTR Tax Reports & Audit Trail Controls",
        shortName: "GST & Audit Trail",
        category: "Tax Compliance",
        description: "Generate GSTR-1, GSTR-3B audit summaries, maintain tamper-proof audit trails, and enforce accounting period locks.",
      },
    ],
  },
  hrms: {
    slug: "hrms",
    badge: "HRMS & Automated Payroll",
    eyebrow: "POWERFUL HR & PAYROLL CAPABILITIES",
    heading: "Employee 360, biometric rosters, leave & 1-click payroll.",
    subtitle: "Manage employee profiles, integrate biometric attendance, automate leave approvals, and generate compliant payslips.",
    features: [
      {
        id: "directory",
        stepNumber: "01",
        title: "Employee 360 Directory & Digital Profiles",
        shortName: "Employee 360°",
        category: "People Master",
        description: "Centralize employee profiles, job titles, department assignments, tax declaration documents, and emergency contacts.",
      },
      {
        id: "attendance",
        stepNumber: "02",
        title: "Biometric Shift Attendance & Rosters",
        shortName: "Shift Attendance",
        category: "Workforce Management",
        description: "Capture biometric punches, track shift rosters, compute overtime, and identify late arrivals or missing punches.",
      },
      {
        id: "leave",
        stepNumber: "03",
        title: "Leave Requests & Automated Approval Flow",
        shortName: "Leave Approval",
        category: "Time-Off Management",
        description: "Automate leave applications, multi-tier manager approvals, paid time-off accruals, and leave balance deductions.",
      },
      {
        id: "payroll",
        stepNumber: "04",
        title: "Automated 1-Click Payroll Engine",
        shortName: "1-Click Payroll",
        category: "Compensation",
        description: "Compute monthly gross salaries, HRA, PF, ESI, TDS tax deductions, and net payouts with instant digital payslips.",
      },
      {
        id: "expenses",
        stepNumber: "05",
        title: "Employee Expense OCR & Asset Allocation",
        shortName: "Expenses & Assets",
        category: "Claims & Logistics",
        description: "Approve employee reimbursement claims with receipt OCR verification and track company hardware asset assignments.",
      },
    ],
  },
  project: {
    slug: "project",
    badge: "Project Management & Costing",
    eyebrow: "POWERFUL PROJECT CAPABILITIES",
    heading: "Milestone Gantt charts, resource utilization & project P&L.",
    subtitle: "Track project phases, allocate billable resources, log timesheets, and control project cost center profitability.",
    features: [
      {
        id: "gantt",
        stepNumber: "01",
        title: "Project Cost Center Milestone Gantt",
        shortName: "Milestone Gantt",
        category: "Timeline Control",
        description: "Visualize project phases, dependencies, milestones, and deliverable deadlines with real-time progress tracking.",
      },
      {
        id: "resources",
        stepNumber: "02",
        title: "Resource Allocation & Utilization Meter",
        shortName: "Resource Capacity",
        category: "Workforce Planning",
        description: "Assign engineering resources to project tasks, monitor billable vs non-billable hours, and prevent resource burnout.",
      },
      {
        id: "costing",
        stepNumber: "03",
        title: "Project Budgeting & Expense Tracking",
        shortName: "Project P&L",
        category: "Cost Governance",
        description: "Track estimated vs actual project costs, vendor expenses, material consumption, and profit margin health.",
      },
      {
        id: "timesheets",
        stepNumber: "04",
        title: "Timesheet Logs & Milestone Approvals",
        shortName: "Timesheets & Tasks",
        category: "Deliverable Tracking",
        description: "Log daily work hours against project tasks, submit supervisor timesheets, and trigger milestone billing events.",
      },
    ],
  },
};

